# Travis CI build file for Kitura-redis.
# Kitura runs on OS X and Linux (Ubuntu v15.10).

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop

notifications:
  slack:
    secure: "dxl90SComYS0d1VPpdvPkXjEHXO9W3dst0u+a7ldfpdGYg6zT4ElF9NHViLbo+dgGhvesnw5BnrHtYbuIGPWU1PgoDFQk9mOqS23m1hJHABxKrOKHx4CZv8tyEBw20OGVtrfk7bHCLdIjbIA7hWoMXr6AdxUL74pbNasGYak4VYTsqZUwqlbQBZ9bozmpf5AafzHxIJK4Z1ltjbYy0kGGE3cuSUE2b1+mRsxAcR5U8eU/7v8eCGIWpQ0mkitAJlRbkJWk+SsYOX8WdE+M0mj5Zgh8MGmW4Sem0mlwEXb/ami/xAAweOsNWRmVJ3u0FkK0qLktYXCHqZ8U/7XwdhQDXBHpVw6L9c11FEqF6fJQU2nFzMRtlgEnYzqVmn2eGp2JwJLaMvw2rbnQzqdMUsKUpOLGZQLnJ0ZNl8QJWwAbFNdBqiuRvEAQeAh+3Wxz7/Xpa64FikMfhgJi0vNr+noGxEnr0kqL3Hsf3F/dadCkBGXrMkeeaKVDlsuSftU2rBbwbQjC9juPHIlfPFjWjnQ6HnGK7cMFvOBmYR17JvP8U8cmKOXoChOHejyTN94AsUNLmFfsqRts50gxZZIMjJfRxTwFocpmEPro9C0PV5tGToRlIvp+i+hP9QBVPT1hVLcRNLT+MjZFPfNth1iQOQPp2F52Tskiu/n9D6JgVUSUnk="

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
    - os: osx
      osx_image: xcode7.3
      sudo: required

before_install:
  - git submodule init
  - git submodule update
  - cd Kitura-Build && git checkout $TRAVIS_BRANCH && cd $TRAVIS_BUILD_DIR

script:
  - echo ">> Let's build and test the '$TRAVIS_BRANCH' branch for Kitura-redis."
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./Kitura-Build/run_kitura_ubuntu_container.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR Kitura-redis ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Kitura-Build/build_kitura_package.sh ; fi
  - echo ">> Build and tests completed. See above for status."
