# Travis CI build file for Kitura-redis.
# Kitura runs on OS X and Linux (Ubuntu v15.10).

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop

notifications:
  slack: ibmswift:RHkwcHYh4kkYVRVzm9nZk5TF

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
    - os: osx
      osx_image: xcode7.2
      sudo: required

before_install:
  - echo "Operating system -> '$TRAVIS_OS_NAME'"
  - echo "Travis build directory -> '$TRAVIS_BUILD_DIR'"
  - git clone https://github.com/IBM-Swift/Kitura-CI.git
  - cp ./Kitura-CI/*.sh $TRAVIS_BUILD_DIR/
  - rm -rf ./Kitura-CI
  - git clone -b master https://$GITHUB_USER:$GITHUB_PWD@github.com/IBM-Swift/DevOps.git

script:
  - echo "About to build and test Kitura-redis for branch '$TRAVIS_BRANCH'."
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./exec_kitura_ubuntu_container.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR Kitura-redis ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build_osx.sh ; fi
  - echo "Build and tests completed. See above for status."
